### PR TITLE
claim vehicle

### PR DESCRIPTION
**Pull request by REDPrjx**
GMS_fnc_spawnMissionHeli : Line -> 83 add "_patrolHeli setVariable ["ExileIsPersistent", false];" 

GMS_fnc_spawnVehicle : Line -> 23 add "_veh setVariable ["ExileIsPersistent", false];" 

GMS_fnc_spawnSubPatrol : Line -> 23 add "_veh setVariable ["ExileIsPersistent", false];" 

GMS_fnc_spawnBoatPatrol : Line -> 23 add "_veh setVariable ["ExileIsPersistent", false];"

### CODE REVIEW

**Comment by Ghostrider-DbD-** [comment]
Quick question - this sets the vehicles up to function with the various claim vehicle scripts floating around?

**Comment by Ghostrider-DbD-** [comment]
Anyway, no problem, I'll add that to the configure vehicle script I think with a check for whether the mod running is Exile.

**Comment by REDPrjx** [comment]
I have only tested this for Exile, it works for the “Claim Vehicles” addon which is on the forums, however it basically only sets the vehicle to be nonpersistent so it should work with others?

**Comment by Ghostrider-DbD-** [comment]
Thank you for the clarification.

**Comment by Ghostrider-DbD-** [comment]
And for sorting this out. It was on my to-do list for sure.

**Comment by Ghostrider-DbD-** [comment]
If you would be kind enough to confirm that the changes have been tested I will merge with the master.

**Comment by REDPrjx** [comment]
I have it running on my live server with 30 players, before the fix i had people complain they couldn’t claim it. After the fix no more complaints. I tested it myself and it works just fine for me! You’re welcome, i’m the one Asking for the DMS reward function, i want to contribute where i can!

**Comment by Ghostrider-DbD-** [comment]
Thank you - so i'll merge this with the Master. Next release will include a re-work of the whole vehicle spawn system so the variable is only set in one script - > better for keeping track of what's what..

**Pull request merged**
